name: CI Dev Android

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-android:
    name: Build Android Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Build APK (dev flavor)
        run: flutter build apk --release --flavor dev -t lib/main_dev.dart
